import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#7da6b3',
        'inverse-on-surface': '#f0f1f1',
        'on-secondary-fixed-variant': '#4a463f',
        'on-primary-fixed-variant': '#224c58',
        'inverse-surface': '#2f3131',
        'primary-fixed': '#bfe9f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'on-error-container': '#93000a',
        'tertiary-container': '#74000e',
        'on-surface-variant': '#41484a',
        secondary: '#625e56',
        'on-surface': '#1a1c1d',
        'outline-variant': '#c0c8ca',
        'inverse-primary': '#a3cddb',
        'primary-fixed-dim': '#a3cddb',
        primary: '#00252e',
        error: '#ba1a1a',
        'on-tertiary-container': '#ff746f',
        outline: '#71787b',
        'on-primary-fixed': '#001f27',
        'surface-variant': '#e2e2e3',
        'primary-container': '#0d3c47',
        'surface-container': '#eeeeee',
        'tertiary-fixed-dim': '#ffb3ae',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#ccc6bc',
        'surface-tint': '#3b6470',
        'on-secondary-container': '#68645c',
        tertiary: '#4c0006',
        'on-tertiary-fixed-variant': '#8e101a',
        'surface-container-highest': '#e2e2e3',
        'on-background': '#1a1c1d',
        'surface-bright': '#f9f9fa',
        surface: '#f9f9fa',
        'secondary-container': '#e8e2d8',
        'surface-container-high': '#e8e8e9',
        'tertiary-fixed': '#ffdad7',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#410004',
        'on-secondary': '#ffffff',
        'surface-dim': '#dadadb',
        'on-secondary-fixed': '#1e1b15',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e8e2d8',
        background: '#f9f9fa',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '20px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        gutter: '32px',
        'section-padding': '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Noto Serif Arabic', 'serif'],
        'headline-sm': ['Noto Serif Arabic', 'serif'],
        'body-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-lg-mobile': ['Noto Serif Arabic', 'serif'],
        'display-lg': ['Noto Serif Arabic', 'serif'],
        'body-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  safelist: [
    'opacity-0',
    'opacity-100',
    'translate-y-0',
    'translate-y-10',
    'transition-all',
    'duration-1000',
    'shadow-lg',
    'shadow-md',
    'py-2',
    'py-4',
    'bg-tertiary-container',
    'text-on-tertiary-container',
    'border-2',
    'border-primary',
    'visible',
  ],
  plugins: [forms, containerQueries],
}
